### ISSUE TITLE
Does module really require perl 5.010001?

### ISSUE THREAD

**Issue by srchulo** [perlancar/perl-Text-CSV_XS-TSV#1]
Currently this line exists:

use 5.010001;

But is it really necessary? I don't see it using any 5.10 features.

**Comment by perlancar** [comment]
"use 5.010001" is my standard preamble in most of my code, so probably not. I think 5.10 is a safe base nowadays now that RHEL 5 is EOL'd. All current Linux distros are 5.10+.

I should probably use dzil plugin like [MinimumPerl] or [MinimumPerlFast] one of these days.

Are you currently using 5.8 or older? On which platform?

**Comment by srchulo** [comment]
Yeah, I think it's fair to say that it's a safe base. I'm on an EOL'd Centos 5.5 with perl 5.8.8.

If you prefer to keep it 5.10, that wouldn't be a big deal for me. This is just an old server we haven't migrated away from yet, but I can easily set `sep_char` etc. manually.

**Comment by perlancar** [comment]
I don't mind removing 5.10 requirement, especially since it's a simple code that won't change much. See the newly released 0.002.

**Comment by srchulo** [comment]
Awesome! Thanks :)
